version: '3.8'

services:

   redis:
      image: redis:6
      ports:
      - "6379:6379"

    web:
      image: python:3.9-slim
    port:
      - 5000:80
    volumes:
      - ./

    db:
      image: postgres:latest
      environment:
        POSTGRES_USER:user
        POSTGRES_PASSWORD:password
        POSTGRES_DB:mydatabase
      ports:
        - "5432:5432"

    web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./etc/nginx/nginx.conf
  